### ISSUE TITLE
Condition Zero autodetecting

### ISSUE THREAD

**Issue by Vladislav4KZ** [Alprnn357/cs16-menu-extended#1]
In your config file, you said that the fifth team class is only available in CSMoE, but in reality it is not so. CS16Client has Condition Zero support, which is turned on by the third secret button in the launcher.

So make this check in your menu configs.
if $gamedir == czero
:*condition zero mode activated, here write commands to show 5 playerclasses*
else
:*show 4 playerclasses*

```
if $gamedir == czero
:touch_addbutton "#Seal Team 6"
:touch_addbutton "#GSG-9"
:touch_addbutton "#SAS"
:touch_addbutton "#GIGN"
:touch_addbutton "#Russian Spetsnaz"
else
:touch_addbutton "#Seal Team 6" // etc...
```

Thanks to this, an additional cvar in the config is not needed and the script will automatically detect the Condition Zero

The same check can be done for csmoe.

**Comment by Vladislav4KZ** [comment]
Or you can do this:
if $gamedir == cstrike
:*here are commands to display 4 classes*
else // Condition Zero or CSMoE
:*show 5 classes*

**Comment by Alprnn357** [comment]
Thanks for the suggestion. I didn't know about the secret button thing and don't know how to enable it. I will take a note it for next release.

**Comment by Alprnn357** [comment]
> In your config file, you said that the fifth team class is only available in CSMoE, but in reality it is not so. CS16Client has Condition Zero support, which is turned on by the third secret button in the launcher.
> 
> So make this check in your menu configs. if $gamedir == czero :_condition zero mode activated, here write commands to show 5 playerclasses_ else :_show 4 playerclasses_
> 
> ```
> if $gamedir == czero
> :touch_addbutton "#Seal Team 6"
> :touch_addbutton "#GSG-9"
> :touch_addbutton "#SAS"
> :touch_addbutton "#GIGN"
> :touch_addbutton "#Russian Spetsnaz"
> else
> :touch_addbutton "#Seal Team 6" // etc...
> ```
> 
> Thanks to this, an additional cvar in the config is not needed and the script will automatically detect the Condition Zero
> 
> The same check can be done for csmoe.

Thank you for the suggestion. I didn't know the secret button thing and don't know how to enable it. I will take a note it for next release.

**Comment by Vladislav4KZ** [comment]
> Thank you for the suggestion. I didn't know the secret button thing and don't know how to enable it. I will take a note it for next release.

Just press many times on the cs16client logo and this button will appear

![Screenshot_20211224-110348.png](https://user-images.githubusercontent.com/22411953/147318785-872c29b1-3d71-4038-8853-93e1cb3fdc22.png)

**Comment by Alprnn357** [comment]
> > Thank you for the suggestion. I didn't know the secret button thing and don't know how to enable it. I will take a note it for next release.
> 
> Just press many times on the cs16client logo and this button will appear
> 
> ![Screenshot_20211224-110348.png](https://user-images.githubusercontent.com/22411953/147318785-872c29b1-3d71-4038-8853-93e1cb3fdc22.png)

Thank you, i will do a new release after the Entity Menu.
